#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AnimaScion.Resource", IsApplication=true)]

namespace AnimaScion
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int spinnerSequence = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int button = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08003d
			public const int ajoutersequence = 2131230781;
			
			// aapt resource value: 0x7f080010
			public const int annee = 2131230736;
			
			// aapt resource value: 0x7f080009
			public const int application = 2131230729;
			
			// aapt resource value: 0x7f080005
			public const int bouttonQuitterAnimation = 2131230725;
			
			// aapt resource value: 0x7f080026
			public const int buttonAjouter = 2131230758;
			
			// aapt resource value: 0x7f080004
			public const int buttonAjouterAnimation = 2131230724;
			
			// aapt resource value: 0x7f080007
			public const int buttonAjouterSequence = 2131230727;
			
			// aapt resource value: 0x7f08002a
			public const int buttonEnvoyerAnimation = 2131230762;
			
			// aapt resource value: 0x7f080012
			public const int buttonInfo = 2131230738;
			
			// aapt resource value: 0x7f080029
			public const int buttonModifierAnimation = 2131230761;
			
			// aapt resource value: 0x7f080037
			public const int buttonModifierSequence = 2131230775;
			
			// aapt resource value: 0x7f080027
			public const int buttonQuitter = 2131230759;
			
			// aapt resource value: 0x7f08002c
			public const int buttonQuitterAnimation = 2131230764;
			
			// aapt resource value: 0x7f080008
			public const int buttonQuitterSequence = 2131230728;
			
			// aapt resource value: 0x7f08002b
			public const int buttonSuprimerAnimation = 2131230763;
			
			// aapt resource value: 0x7f080038
			public const int buttonSuprimerSequence = 2131230776;
			
			// aapt resource value: 0x7f08000e
			public const int copyright = 2131230734;
			
			// aapt resource value: 0x7f080011
			public const int createur = 2131230737;
			
			// aapt resource value: 0x7f08000b
			public const int dev = 2131230731;
			
			// aapt resource value: 0x7f08000f
			public const int droits = 2131230735;
			
			// aapt resource value: 0x7f08003b
			public const int envoyeranimation = 2131230779;
			
			// aapt resource value: 0x7f08000d
			public const int idutilisateur = 2131230733;
			
			// aapt resource value: 0x7f080040
			public const int info = 2131230784;
			
			// aapt resource value: 0x7f08000c
			public const int langage = 2131230732;
			
			// aapt resource value: 0x7f080025
			public const int listAnimation = 2131230757;
			
			// aapt resource value: 0x7f080039
			public const int menu = 2131230777;
			
			// aapt resource value: 0x7f08003a
			public const int modifieranimation = 2131230778;
			
			// aapt resource value: 0x7f080041
			public const int modifiersequence = 2131230785;
			
			// aapt resource value: 0x7f08003f
			public const int nouvelleanimation = 2131230783;
			
			// aapt resource value: 0x7f08003e
			public const int quitter = 2131230782;
			
			// aapt resource value: 0x7f080006
			public const int spinnerAllSequence = 2131230726;
			
			// aapt resource value: 0x7f080028
			public const int spinnerSequence = 2131230760;
			
			// aapt resource value: 0x7f08003c
			public const int suprimeranimation = 2131230780;
			
			// aapt resource value: 0x7f080042
			public const int suprimersequence = 2131230786;
			
			// aapt resource value: 0x7f080013
			public const int tableLayout1 = 2131230739;
			
			// aapt resource value: 0x7f080014
			public const int tableRow1 = 2131230740;
			
			// aapt resource value: 0x7f080017
			public const int tableRow2 = 2131230743;
			
			// aapt resource value: 0x7f08001a
			public const int tableRow3 = 2131230746;
			
			// aapt resource value: 0x7f08001d
			public const int tableRow4 = 2131230749;
			
			// aapt resource value: 0x7f080015
			public const int textView10 = 2131230741;
			
			// aapt resource value: 0x7f080018
			public const int textView11 = 2131230744;
			
			// aapt resource value: 0x7f08001b
			public const int textView12 = 2131230747;
			
			// aapt resource value: 0x7f08001e
			public const int textView19 = 2131230750;
			
			// aapt resource value: 0x7f080003
			public const int toggleBoucle = 2131230723;
			
			// aapt resource value: 0x7f080036
			public const int toggleFill = 2131230774;
			
			// aapt resource value: 0x7f080035
			public const int toggleRotation = 2131230773;
			
			// aapt resource value: 0x7f080000
			public const int txtAnimation = 2131230720;
			
			// aapt resource value: 0x7f080002
			public const int txtBoucle = 2131230722;
			
			// aapt resource value: 0x7f080021
			public const int txtContenuBoucle = 2131230753;
			
			// aapt resource value: 0x7f080023
			public const int txtContenuNbrSequence = 2131230755;
			
			// aapt resource value: 0x7f080020
			public const int txtContenuNomAnimation = 2131230752;
			
			// aapt resource value: 0x7f080016
			public const int txtContenuNomSequence = 2131230742;
			
			// aapt resource value: 0x7f080019
			public const int txtContenuPosition = 2131230745;
			
			// aapt resource value: 0x7f08001f
			public const int txtContenuRotation = 2131230751;
			
			// aapt resource value: 0x7f08001c
			public const int txtContenuTaille = 2131230748;
			
			// aapt resource value: 0x7f080024
			public const int txtNbrAnimation = 2131230756;
			
			// aapt resource value: 0x7f080022
			public const int txtNbrSequence = 2131230754;
			
			// aapt resource value: 0x7f080001
			public const int txtNomAnimation = 2131230721;
			
			// aapt resource value: 0x7f08002f
			public const int txtNomFichier = 2131230767;
			
			// aapt resource value: 0x7f08002d
			public const int txtNomSequence = 2131230765;
			
			// aapt resource value: 0x7f08002e
			public const int txtParam1 = 2131230766;
			
			// aapt resource value: 0x7f080030
			public const int txtParam2 = 2131230768;
			
			// aapt resource value: 0x7f080031
			public const int txtParam3 = 2131230769;
			
			// aapt resource value: 0x7f080032
			public const int txtParam4 = 2131230770;
			
			// aapt resource value: 0x7f080033
			public const int txtParam5 = 2131230771;
			
			// aapt resource value: 0x7f080034
			public const int txtRotation = 2131230772;
			
			// aapt resource value: 0x7f08000a
			public const int version = 2131230730;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int AjouterAnimation = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int AjouterSequence = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Info = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int ListeAllSequence = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int ListeAnimation = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int ListeSequence = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int Main = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int ModifierAnimation = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int ModifierSequence = 2130968584;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int OptionMenuAnimation = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int OptionMenuMain = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int OptionMenuSequence = 2131165186;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f05001e
			public const int actualiser = 2131034142;
			
			// aapt resource value: 0x7f050013
			public const int addAnimation = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int addSequence = 2131034132;
			
			// aapt resource value: 0x7f05000d
			public const int annee = 2131034125;
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050006
			public const int application = 2131034118;
			
			// aapt resource value: 0x7f050012
			public const int boucle = 2131034130;
			
			// aapt resource value: 0x7f05000b
			public const int copyright = 2131034123;
			
			// aapt resource value: 0x7f05000e
			public const int createur = 2131034126;
			
			// aapt resource value: 0x7f050008
			public const int dev = 2131034120;
			
			// aapt resource value: 0x7f05000c
			public const int droits = 2131034124;
			
			// aapt resource value: 0x7f050017
			public const int envoyer = 2131034135;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int info = 2131034116;
			
			// aapt resource value: 0x7f050009
			public const int langage = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int license = 2131034122;
			
			// aapt resource value: 0x7f050002
			public const int menu = 2131034114;
			
			// aapt resource value: 0x7f050015
			public const int modifieranimation = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int modifiersequence = 2131034134;
			
			// aapt resource value: 0x7f05000f
			public const int nbranimation = 2131034127;
			
			// aapt resource value: 0x7f050011
			public const int nbrsequence = 2131034129;
			
			// aapt resource value: 0x7f050010
			public const int nomanimation = 2131034128;
			
			// aapt resource value: 0x7f05001a
			public const int nomsequence = 2131034138;
			
			// aapt resource value: 0x7f050003
			public const int nouvelleanimation = 2131034115;
			
			// aapt resource value: 0x7f05001b
			public const int position = 2131034139;
			
			// aapt resource value: 0x7f050005
			public const int quitter = 2131034117;
			
			// aapt resource value: 0x7f05001d
			public const int rotation = 2131034141;
			
			// aapt resource value: 0x7f05001f
			public const int spinnerPrompt = 2131034143;
			
			// aapt resource value: 0x7f050018
			public const int suprimeranimation = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int suprimersequence = 2131034137;
			
			// aapt resource value: 0x7f05001c
			public const int taille = 2131034140;
			
			// aapt resource value: 0x7f050007
			public const int version = 2131034119;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
